### ISSUE TITLE
Logo = 0 not hiding the Cappasity logo at all

### ISSUE THREAD

**Issue by aagasi** [CappasityTech/API#21]
We are embedding an iframe with the 3D image of a product and it also prints the Cappasity logo and the Powered by Cappasity watermark.

We are passing logo=0 as a parameter in the src but it's not hidding the logo at all.

Any idea how to achieve this?

Thanks,

**Comment by cappasity** [comment]
This feature is available for Enterprise clients only. Please contact our sales team support@cappasity.com
