### ISSUE TITLE
Attribute "language" is ignored on exchange request

### ISSUE THREAD

**Issue by matthias-willhaben** [CappasityTech/API#22]
When I add the "language" attribute into the `/api/oembed/marketplace` request, it is not appended on the url of the iframe. However, when I manually add the query parameter to the url, the language changes as expected.

**Comment by aleksxor** [comment]
Fixed. Let me know if it works for you now.

**Comment by matthias-willhaben** [comment]
Works now. Thanks for the super quick response!
